\documentclass{article}
\usepackage{enumitem}
\usepackage{ amssymb }
\usepackage{ textcomp }
\usepackage{longtable}
\usepackage{amsmath,tabu}
\topmargin=-0.45in
\evensidemargin=0in
\oddsidemargin=0in
\textwidth=6.5in
\textheight=9.0in
\headsep=0.25in

\title{Processing HiChIP Data at OMRF}
\author{Caleb Lareau}
\date{Last updated: \today}


\begin{document}
\maketitle

\section{About}
Welcome to the wonderful world of HiChIP preprocessing! 

\end{document}
